default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: crm
  password: crm


development:
  <<: *default
  database: crm_development

test:
  <<: *default
  database: crm_test

production:
  primary: &primary_production
    <<: *default
    database: crm_production
    username: crm
    password: <%= ENV["CRM_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: crm_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: crm_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: crm_production_cable
    migrations_paths: db/cable_migrate
